version: '3'
services:
  ### Postgres #############################################
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PROJECT_DB=${DB_DATABASE}
      - TZ=GMT
      - PGTZ=GMT
    ports:
      - '5432:5432'
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh

volumes:
  postgres:
    driver: local
